[project]
name = "odoo-addons-sygel-technology-sy-pos"
version = "18.0.20260306.0"
dependencies = [
    "odoo-addon-pos_item_counter==18.0.*",
    "odoo-addon-pos_session_closing_note==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
